// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcTaskManagerAPI.Identity;

namespace MvcTaskManagerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240205071344_taskadded")]
    partial class taskadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int>("CountryID");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<bool>("ReceiveNewsLetter");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.ClientLocation", b =>
                {
                    b.Property<int>("ClientLocationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientLocationName");

                    b.HasKey("ClientLocationID");

                    b.ToTable("ClientLocations");

                    b.HasData(
                        new { ClientLocationID = 1, ClientLocationName = "New Delhi" },
                        new { ClientLocationID = 2, ClientLocationName = "Boston" },
                        new { ClientLocationID = 3, ClientLocationName = "Tokyo" },
                        new { ClientLocationID = 4, ClientLocationName = "Sydney" },
                        new { ClientLocationID = 5, ClientLocationName = "Berlin" },
                        new { ClientLocationID = 6, ClientLocationName = "Paris" },
                        new { ClientLocationID = 7, ClientLocationName = "Rio de			Janeiro" },
                        new { ClientLocationID = 8, ClientLocationName = "Cape Town" }
                    );
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName");

                    b.HasKey("CountryID");

                    b.ToTable("Countries");

                    b.HasData(
                        new { CountryID = 1, CountryName = "China" },
                        new { CountryID = 2, CountryName = "United States" },
                        new { CountryID = 3, CountryName = "Indonesia" },
                        new { CountryID = 4, CountryName = "Brazil" },
                        new { CountryID = 5, CountryName = "Pakistan" },
                        new { CountryID = 6, CountryName = "Nigeria" },
                        new { CountryID = 7, CountryName = "Bangladesh" },
                        new { CountryID = 8, CountryName = "Russia" },
                        new { CountryID = 9, CountryName = "Japan" },
                        new { CountryID = 10, CountryName = "Mexico" },
                        new { CountryID = 11, CountryName = "Philippines" },
                        new { CountryID = 12, CountryName = "Vietnam" },
                        new { CountryID = 13, CountryName = "Ethiopia" },
                        new { CountryID = 14, CountryName = "Egypt" },
                        new { CountryID = 15, CountryName = "Germany" },
                        new { CountryID = 16, CountryName = "Iran" },
                        new { CountryID = 17, CountryName = "Turkey" },
                        new { CountryID = 18, CountryName = "Congo" },
                        new { CountryID = 19, CountryName = "Thailand" },
                        new { CountryID = 20, CountryName = "France" },
                        new { CountryID = 21, CountryName = "United Kingdom" },
                        new { CountryID = 22, CountryName = "Italy" },
                        new { CountryID = 23, CountryName = "South Africa" },
                        new { CountryID = 24, CountryName = "South Korea" },
                        new { CountryID = 25, CountryName = "Vatican City" }
                    );
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("ClientLocationID");

                    b.Property<DateTime>("DateOfStart");

                    b.Property<string>("ProjectName");

                    b.Property<string>("Status");

                    b.Property<int?>("TeamSize");

                    b.HasKey("ProjectID");

                    b.HasIndex("ClientLocationID");

                    b.ToTable("Projects");

                    b.HasData(
                        new { ProjectID = 1, Active = true, ClientLocationID = 1, DateOfStart = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), ProjectName = "Project A", Status = "In Progress", TeamSize = 10 },
                        new { ProjectID = 2, Active = false, ClientLocationID = 2, DateOfStart = new DateTime(2022, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), ProjectName = "Project B", Status = "Completed", TeamSize = 8 },
                        new { ProjectID = 3, Active = true, ClientLocationID = 3, DateOfStart = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), ProjectName = "Project C", Status = "On Hold", TeamSize = 15 }
                    );
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Id");

                    b.Property<string>("SkillLevel");

                    b.Property<string>("SkillName");

                    b.HasKey("SkillID");

                    b.HasIndex("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignedTo");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CurrentStatus");

                    b.Property<int>("CurrentTaskStatusID");

                    b.Property<string>("Description");

                    b.Property<DateTime>("LastUpdatedOn");

                    b.Property<int>("ProjectID");

                    b.Property<string>("TaskName");

                    b.Property<int>("TaskPriorityID");

                    b.HasKey("TaskID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectID");

                    b.HasIndex("TaskPriorityID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.TaskPriority", b =>
                {
                    b.Property<int>("TaskPriorityID");

                    b.Property<string>("TaskPriorityName");

                    b.HasKey("TaskPriorityID");

                    b.ToTable("TaskPriorities");

                    b.HasData(
                        new { TaskPriorityID = 1, TaskPriorityName = "Urgent" },
                        new { TaskPriorityID = 2, TaskPriorityName = "Normal" },
                        new { TaskPriorityID = 3, TaskPriorityName = "Below Normal" },
                        new { TaskPriorityID = 4, TaskPriorityName = "Low" }
                    );
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.TaskStatus", b =>
                {
                    b.Property<int>("TaskStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TaskStatusName");

                    b.HasKey("TaskStatusID");

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new { TaskStatusID = 1, TaskStatusName = "Holding" },
                        new { TaskStatusID = 2, TaskStatusName = "Prioritized" },
                        new { TaskStatusID = 3, TaskStatusName = "Started" },
                        new { TaskStatusID = 4, TaskStatusName = "Finished" },
                        new { TaskStatusID = 5, TaskStatusName = "Reverted" }
                    );
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.TaskStatusDetail", b =>
                {
                    b.Property<int>("TaskStatusDetailID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime>("StatusUpdationDateTime");

                    b.Property<int>("TaskID");

                    b.Property<int>("TaskStatusID");

                    b.Property<string>("UserID");

                    b.HasKey("TaskStatusDetailID");

                    b.HasIndex("TaskID");

                    b.HasIndex("TaskStatusID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskStatusDetails");
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Identity.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");


                    b.ToTable("ApplicationRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Project", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Models.ClientLocation", "ClientLocation")
                        .WithMany()
                        .HasForeignKey("ClientLocationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Skill", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id");
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.Task", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo");

                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("MvcTaskManagerAPI.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcTaskManagerAPI.Models.TaskPriority", "TaskPriority")
                        .WithMany()
                        .HasForeignKey("TaskPriorityID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MvcTaskManagerAPI.Models.TaskStatusDetail", b =>
                {
                    b.HasOne("MvcTaskManagerAPI.Models.Task")
                        .WithMany("TaskStatusDetails")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcTaskManagerAPI.Models.TaskStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcTaskManagerAPI.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
